### PR TITLE
remove the default router so the ingress operator can create it

### PR DESCRIPTION
**Pull request by AndreaM12345**

### CODE REVIEW

**Review by relyt0925 — CHANGES_REQUESTED** [review]
need to see test  logs internally first before merging

**Comment by AndreaM12345** [comment]
Cluster I manually tested with:
```
ayma-oc4-34c                      bpgoogf10fh7gom9v5n0   normal          18 hours ago   3         Dallas     4.3.3_1284_openshift   Default               classic   
```
tested that things can get created and past through the routers getting created:

```
kubectl get svc -n openshift-ingress
ku	 deNAME                        TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
router-default              LoadBalancer   172.21.85.35     52.116.185.134   80:31340/TCP,443:32375/TCP   4h23m
router-default-3            LoadBalancer   172.21.160.191   52.116.185.132   80:30958/TCP,443:30865/TCP   108m
router-default-4            LoadBalancer   172.21.117.63    52.116.185.130   80:32659/TCP,443:30764/TCP   87m
router-internal-default     ClusterIP      172.21.228.12    <none>           80/TCP,443/TCP,1936/TCP      18h
router-internal-default-3   ClusterIP      172.21.44.36     <none>           80/TCP,443/TCP,1936/TCP      108m
router-internal-default-4   ClusterIP      172.21.155.11    <none>           80/TCP,443/TCP,1936/TCP      87m
tea-svc                     ClusterIP      172.21.158.192   <none>           80/TCP                       73m
```

output of curl cmds to the router created to test things are working:

```
macbook-pro:~ andreama$ curl -kv http://foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud/tea-cafe2
*   Trying 52.116.185.130...
* TCP_NODELAY set
* Connected to foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud (52.116.185.130) port 80 (#0)
> GET /tea-cafe2 HTTP/1.1
> Host: foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Cache-Control: no-cache
< Content-length: 0
< Location: https://foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud/tea-cafe2
< 
* Connection #0 to host foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud left intact
macbook-pro:~ andreama$ curl -kv https://foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud/tea-cafe2
*   Trying 52.116.185.130...
* TCP_NODELAY set
* Connected to foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud (52.116.185.130) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=ayma-oc4-34c.us-south.stg.containers.appdomain.cloud
*  start date: Mar  5 22:34:21 2020 GMT
*  expire date: Jun  3 22:34:21 2020 GMT
*  issuer: CN=Fake LE Intermediate X1
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /tea-cafe2 HTTP/1.1
> Host: foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.13.8
< Date: Fri, 06 Mar 2020 19:20:47 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Expires: Fri, 06 Mar 2020 19:20:46 GMT
< Cache-Control: no-cache
< Set-Cookie: f1fcf6409adba2b6ea19136f78e18f39=e85d7352260792f82c867379d14831ca; path=/; HttpOnly; Secure
< 
<!DOCTYPE html>
<html>
<head>
<title>Hello World</title>
<link href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAGPElEQVR42u1bDUyUdRj/iwpolMlcbZqtXFnNsuSCez/OIMg1V7SFONuaU8P1MWy1lcPUyhK1uVbKcXfvy6GikTGKCmpEyoejJipouUBcgsinhwUKKKJ8PD3vnzsxuLv35Q644+Ue9mwH3P3f5/d7n6/3/3+OEJ/4xCc+8YQYtQuJwB0kIp+JrzUTB7iJuweBf4baTlJ5oCqw11C/JHp+tnqBb1ngT4z8WgReTUGbWCBGq0qvKRFcHf4eT/ZFBKoLvMBGIbhiYkaQIjcAfLAK+D8z9YhjxMgsVUGc84+gyx9AYD0khXcMfLCmUBL68HMZ+PnHxyFw3Uwi8B8hgJYh7j4c7c8PV5CEbUTUzBoHcU78iIl/FYFXWmPaNeC3q4mz5YcqJPI1JGKql2Z3hkcjD5EUznmcu6qiNT+Y2CPEoH3Wm4A/QERWQFe9QQ0caeCDlSZJrht1HxG0D3sOuCEiCA1aj4ZY3Ipzl8LiVtn8hxi5zRgWM8YYPBODF/9zxOLcVRVs+YGtwFzxCs1Bo9y+avBiOTQeUzwI3F5+kOwxsXkkmWNHHrjUokqtqtSyysW5gUHV4mtmZEHSdRkl+aELvcFIRN397gPPXD4ZgbxJW1S5OJdA60MgUAyHu1KfAz+pfCUtwr+HuQc8ORQ1jK4ZgGsTvcY5uQP5oYkY2HfcK5sGLpS6l1xZQwNn7Xkedp3OgMrWC1DX0Qwnms/A1rK9cF9atNVo18DP/3o5fF99BGo7LFDRWgMJJQaYQv/PyOcHySP0TITrBIhYb+WSHLrlNGEx5NeXgj2paW8C5rs46h3Dc3kt3G2Ogr9aqoes+f5RvbL1aJ5iXnKnxkfIEoB3N/zHeHAmF9ovwryvYvC9TysnICkEonPX212vvOU8+As6eS+QCDAw0aNLABq6LO8DkJMSSznMMEfScFFGwCJYXbDV7lq17RYIQu+QTYpjRUBM3gZQIt+cOwyTpWRpYBQRsKrgU4ceNS4JkCSxLI1+ZsIS0NvXB6sLE/tL5EQkQJKOm52YON9y7glqJkCSOqzrD6Uvc1wZ1EBA07V/IafmN4ckHG+ugJkSEHuVQQ0ENFy9BLP3R0NR4ymHJGRWFWBnZ6fPVwMBF9EDgrD2z0USqtoaHJKw49SBoZ2dWggIxmcEsvspYLLi4PKNDrvv68OfuKLt/68MqiJAan4Q0IpDm6G7r8fue692X4fI7PiByqA6AqygNh0XHIaClDOkpz9aGVRJABo8CTP+3sqfHZJQeqkSgvHZn+xaqEICKAlhECSGO60MWdVF4IcesDL/ExUSYN3okCrD31fqHZLwcWkq5owPVUoA3UcIgdBv10BrV7vdz3b39kBhw0kVE2BNirG/bqRghyPqIcBKQkKJcVgE1LQ1wR3S5ooqCDBKlSEUzGdyFBNwvq1RTQT0b4BOF5+BgoayCUqAtTLMSXsRzl6uHX8EONoUtXS2KCfAusOsyVwFLV1tznNAuzflAGxb+R/esGuodDcD0bUVbYLelhRf/mWD08ogdYtTjNwYbIsrORhBIwJMPOTWHh1i6Lriz107FUKviivcZvfp8WZvN8TmbVS2rtsHI8mMtn9gSe50KAz79yWw8490OGYpp8lsTUGictd3EA6PHVwB20+mYUNURo/aMs4dhqjsdcoOWGxH5yYu0g0P0EzFBd7DxZoVHY7aHmWtB6VunwhLB6P0gFULk6zhJnvnBw5HW9D9N5GkpQEjMBcQOg+JMBNxjMZgHISawvGZHiKw+0mybv5ozP0txgvk07AQvWxAoh98sXsur3RmwMStxIud9fiIzMAIXTV6yNqxHaH7gg1GA7bgxVvHfEjq1hAl10ZM/A46gO0x0bOPoiHpSEDvsMZhXVVbVRL4TLz2E140EK1dgsnnd9mBaHcmwuigJHeCGLkXvHNaNHOBP4J/HYmoGbGwsJU1ka0nAvM2ht40758ZNmvvRRJ24l3roMa7MxVq4jpRdyMRc8bh9wR0TyIRWdR9hzNXaJs3Ftif6KDWuBcBH0hErky2bNraV5E9jcBjiapE1ExHkO8iEY1OvjLTjAkugezh7ySqFUPoXHTtZAR7ncY4rRrYYgtcCtGHPUgmjEhPmiKXjXc/l4g6HfGJT3ziEw/If86JzB/YMku9AAAAAElFTkSuQmCC" rel="icon" type="image/png" />
<style>
body {
  margin: 0px;
  font: 20px 'RobotoRegular', Arial, sans-serif;
  font-weight: 100;
  height: 100%;
  color: #0f1419;
}
div.info {
  display: table;
  background: #e8eaec;
  padding: 20px 20px 20px 20px;
  border: 1px dashed black;
  border-radius: 10px;
  margin: 0px auto auto auto;
}
div.info p {
    display: table-row;
    margin: 5px auto auto auto;
}
div.info p span {
    display: table-cell;
    padding: 10px;
}
img {
    width: 176px;
    margin: 36px auto 36px auto;
    display:block;
}
div.smaller p span {
    color: #3D5266;
}
h1, h2 {
  font-weight: 100;
}
div.check {
    padding: 0px 0px 0px 0px;
    display: table;
    margin: 36px auto auto auto;
    font: 12px 'RobotoRegular', Arial, sans-serif;
}
#footer {
    position: fixed;
    bottom: 36px;
    width: 100%;
}
#center {
    width: 400px;
    margin: 0 auto;
    font: 12px Courier;
}

</style>
<script>
var ref;
function checkRefresh(){
    if (document.cookie == "refresh=1") {
        document.getElementById("check").checked = true;
        ref = setTimeout(function(){location.reload();}, 1000);
    } else {
    }
}
function changeCookie() {
    if (document.getElementById("check").checked) {
        document.cookie = "refresh=1";
        ref = setTimeout(function(){location.reload();}, 1000);
    } else {
        document.cookie = "refresh=0";
        clearTimeout(ref);
    }
}
</script>
</head>
<body onload="checkRefresh();">
<img alt="NGINX Logo" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAWAAAABICAMAAAD/N9+RAAAAVFBMVEUAAAAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQAAmQDBect+AAAAG3RSTlMAB0AY8SD5SM82v1npsJ/YjSl0EVLftqllgMdZgsoQAAAHd0lEQVR42szZ6XabMBCG4ZGFxSazLzZz//fZc9I4JpbEN8LQ0/dnGwJ5DJGG0HdpM9kkuzVXiqussmRpLrRdnwqDp9ePyY7zXdFbqptHOz00RTVUxWiyquvJ26Upknp2/heWN0Uyzt3qYtKMn805ybsW/LdK01YVC6sVELH81XJ9o6j5q6Qkcepe83dJp8ipf161HSgm1TyPK5//cuN1d5KmE342bsnkLK6hre78LNG0KuWfOrFDwats69w8ln+qFIlrx9Vxf8808e8eJGx9YEXhCpZ3kX2gfFtbrX4m05IonTE7wsGLnpXY1/Kqr3v/5r+NcAOvy8HXCRt74W+alH568KqCJKmM37LafVhe3ZTU1/mmA7uV9Ar8vPjZVCPDZI+CDdwFC68yIooZnbhmIAx8XyoZu5mcYO9HzhSo47gGCqR53ULPlAGPkuyazJVeKWYsjH15Djy/VhPO8LoM/OJE4XNfeJ19LUfRj18KF9gLA2GZL4/UsLdFHQVccWyTCDjZD9wm7Kt2PgIgjH3ZBlf46iDgnOO7nwusavZmVoCaPU0q1pcnshyoOwa44PiS66nANw7U0isbK5x7j3gQB0uPAB54T8WZwA/RHrxhLIx9TbsBnLSfA6uRd9WdBzywCFiNUcJ5wr4eRByu7j8G7nhfpj0LuE0A8OtsSBj7ZooIL+dyYLxFm27+EvfSzgHua/GYXrK3Qol9a03bwNxEAeMt2ix/bptzgCeGwFhY7ouAufwIOA/PSni3nJ8B3DAElgtjXwxs8k+Al/BdiVfDWh0PPDAAjhXGvgTnVjkwujzbk1t4TWkOB24TBBwrjH2JQZnaC6xGsPdCT296MHA/MgKWC2NfL7Blp2ov8AM88/gNbX8osCrc5xMAA2Ho6wIXHTt1+4C1iZwMW8NvzYcCN67vAICBMPZ1galip3QXcAXHXzyVlB8AYyiT5wAYCWNfF1gtYGYWAufhNynyTWqiDwPOjeelnQiYShMQBr5+YNIWzMwy4CX69afv1NNRwHr07FKEwDT4hTPs6wL7P+tCxQKXm/eifJ963wmMF7hCYWBXGJdpAsBUopkZAyv3j3+i9PUtTa/U9VcAGC1wmgAwFsa+LnBooLxj4K0t2qjo8AAwWuAIAO8TznoSANMEZmYErA14p3EyMF7gSgLAQBj4ImBVg5kZAM/8u4VAJwJ7l+2GADAQBr4A2D+1Z0oMnKM3Y2cD4wUOAANh5IuB6cJOsxg4Q0eeCwwXuFETBnZLDfSVA1NwZsbAJXwN/C+B7771BAAjYeyLgX0z8yACVlawx1NaXh+5TcMLHACGwtgXA6OZ2QUObdGsorfabjIsr4wcNOACB4CBMPLFwOHpcuwx8NWgLXTJURW0H1gtngUOA8cLLz1FAsOZWQ4MfFH5B8CV7x75b4D/NHduS47CMBCVwYFAiDEmCQT+/z/3ZWumah1otZdL/MxMZc5gybJanU8tLI9DhF8PESXJ10k64PAxyn1LiPisMhr/N8kNHF+bpwPOis95+juS3IJOrsgQYBlXj2mWFVHRgHGC+4pj2kKjbG4ufKGRLmdtTTJgc12WKn1BofE7zBTXzAhwtlIqP9h5gmTAbq1xcHqpvBbHBgRY7suXPTl/ROMB4wR36mUPKjXnNwLcrVxXXimRZTLgDBSiZ15XYj3XAwAWv3zh7gnAXtIAx6Etnq888cIdX/fZDgDul1tGvf4Vtn0S4M8J7i7ROq1lhCVHzzwGvBpYbJ5AOEgq4EEzZn5K01MrmqvNOmDTLrft+8FSRzQecFBpO05p26tlnw7oIso14YnJ3i5aL6DF0wMuleqkM4Qn+smcAKRTL1Y65UDQVAO+WK2+7gTplH54usjWAXek+K+LCuxEwGMLul0R4EPFfz8L18zzKmDxIKSCN95LIuBGr3GujpevErqxGQDuLaPuyUAfBAPGg6Mx4OME2DhQVgUJWAIzQnBFfRAeMI5N1XEjBBiwjCxg0+qHYG7wt/GA8capDh+CqYkpCoykjPKWesio2gywEwD4qDEuDNjUJGCptQqUAB5MB3w1APBhg4gYsPQtCbib00Zpi3wrwM1FAOBjR2lrZBXCARY3J623bAS4yAQAPnIYHAOWkgSc2xS+T7MV4CAA8LF2BhiwBAwYP4+lPBsBdgIAH2XIgQHjTf+SrRw5auEAG5Dg9ID3t5TBgM3EWR88eMAVCVieYM5aDXgHUyQAmKiZR9nIFckJC/gFnALUgHew9QKAiZq5A3+EXspDAw7gP64GvIcxXQvfHl2B7tiozSf+y1JSNQ31gRYDQb6HteKQ4B3s4QucflRrDW8OKiHBujCO3s0u5qAjwKR0vnkDozL1emgd5W6EWa1ud7l97G0n3jhYzACOEMlHtVpjeBA/mLf/7IOoQsa7y+b7GDR3Rbw98fKQLy+5xv7VIXowIhy1ztUfbdzLYrz7cbrvRb/K+nf7wPPQpAXsEQ/7l2AXW97/AGkCwaNsIif8zU3y5eZaO/mK/jKDV1s872/Fz11K5TLE1zzEiP1km8ndDMcj3JvmFfqdvubhD8TgHPiN+LViAAAAAElFTkSuQmCC"/>
<div class="info">
<p><span>Server&nbsp;address:</span> <span>172.30.20.30:80</span></p>
<p><span>Server&nbsp;name:</span> <span>tea-rc-bhq86</span></p>
<p class="smaller"><span>Date:</span> <span>06/Mar/2020:19:20:47 +0000</span></p>
<p class="smaller"><span>URI:</span> <span>/tea-cafe2</span></p>
</div>
<div class="check"><input type="checkbox" id="check" onchange="changeCookie()"> Auto Refresh</div>
    <div id="footer">
        <div id="center" align="center">
            Request ID: 92ac9a5861512863a7e9edcc6f609d06<br/>
            &copy; NGINX, Inc. 2018
        </div>
    </div>
</body>
</html>

* Connection #0 to host foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud left intact
macbook-pro:~ andreama$
```

Display of ingress resource files
```
macbook-pro:armada-dns-microservice andreama$ kubectl get ing
NAME              HOSTS                                                                                             ADDRESS   PORTS     AGE
tea2-ingress      ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud                  80        3h17m
teafoo4-ingress   foo2.ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud             80, 443   55m
```

showing that it has an ingress-operator deployment:
```
macbook-pro:armada-dns-microservice andreama$ kubectl get deployment -n openshift-ingress-operator
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
ingress-operator   1/1     1            1           19h
```

showing that the IBMCloud Platform showing up:
```
macbook-pro:armada-dns-microservice andreama$ oc get infrastructures.config.openshift.io/cluster -o yaml
apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"Infrastructure","metadata":{"annotations":{},"creationTimestamp":null,"name":"cluster"},"spec":{"cloudConfig":{"name":""}},"status":{"apiServerInternalURI":"https://c100-e.containers.pretest.cloud.ibm.com:30812","apiServerURL":"https://c100-e.containers.pretest.cloud.ibm.com:30812","etcdDiscoveryDomain":"ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud","infrastructureName":"kubernetes","platform":"IBMCloud","platformStatus":{"type":"IBMCloud"}}}
  creationTimestamp: 2020-03-05T23:38:25Z
  generation: 1
  name: cluster
  resourceVersion: "313"
  selfLink: /apis/config.openshift.io/v1/infrastructures/cluster
  uid: 1e6b1ea8-ff2d-4a0f-b064-649beb92b3b1
spec:
  cloudConfig:
    name: ""
status:
  apiServerInternalURI: https://c100-e.containers.pretest.cloud.ibm.com:30812
  apiServerURL: https://c100-e.containers.pretest.cloud.ibm.com:30812
  etcdDiscoveryDomain: ayma-oc4-34c-1e7743ca80a399c9cff4eaf617434c72-0000.us-south.stg.containers.appdomain.cloud
  infrastructureName: kubernetes
  platform: IBMCloud
  platformStatus:
    type: IBMCloud
macbook-pro:armada-dns-microservice andreama$ 
```

**Review by relyt0925 — APPROVED** [review]

**Pull request merged**
